#!/usr/bin/env python3
"""
Universal Voting System - Automated Deployment Script
Creates a customized deployment package for any organization
"""

import os
import shutil
import argparse
import json
from pathlib import Path

def create_env_file(org_name, election_title, positions, admin_token, output_dir):
    """Create a customized .env file for the organization"""
    env_content = f"""# {org_name} - Voting System Configuration
# Generated by Universal Voting System Deployment Script

# Organization Configuration
ORGANIZATION_NAME="{org_name}"
ELECTION_TITLE="{election_title}"

# Admin Configuration
ADMIN_TOKEN="{admin_token}"

# Election Positions (comma-separated)
ELECTION_POSITIONS="{positions}"

# Database Configuration (set by deployment platform)
# DATABASE_URL=postgresql://...

# Flask Configuration
FLASK_ENV=production
"""

    env_path = os.path.join(output_dir, '.env')
    with open(env_path, 'w') as f:
        f.write(env_content)

    print(f"Created .env file: {env_path}")
    return env_path

def create_deployment_guide(org_name, election_title, positions, admin_token, output_dir):
    """Create a customized deployment guide for the client"""

    positions_list = positions.split(',')
    positions_formatted = '\n'.join(f"- {pos.strip()}" for pos in positions_list)

    guide_content = f"""# {org_name} - Voting System Deployment Guide

## Welcome to Your Custom Voting System!

Your voting system has been configured for:
- **Organization**: {org_name}
- **Election**: {election_title}
- **Positions**: {len(positions_list)} positions configured
- **Admin Token**: `{admin_token}` (keep this secure!)

## Quick Deployment (Recommended)

### Option 1: Render (Easiest - Recommended)
1. **Create Render Account**: Go to [render.com](https://render.com)
2. **Connect Repository**: Link this GitHub repository
3. **Set Environment Variables**: Copy from the `.env` file provided
4. **Deploy**: Click "Create Web Service"
5. **Done!**: Your voting system will be live in 5-10 minutes

### Option 2: Railway
1. **Create Railway Account**: Go to [railway.app](https://railway.app)
2. **Connect Repository**: Link your GitHub repo
3. **Add Variables**: Set the environment variables from `.env`
4. **Deploy**: Railway handles the rest automatically

### Option 3: Heroku
1. **Install Heroku CLI**: `npm install -g heroku`
2. **Login**: `heroku login`
3. **Create App**: `heroku create your-app-name`
4. **Set Variables**: `heroku config:set ORGANIZATION_NAME="{org_name}"` etc.
5. **Deploy**: `git push heroku main`

## ⚙️ Environment Variables (Already Configured)

Your `.env` file contains:
```bash
ORGANIZATION_NAME="{org_name}"
ELECTION_TITLE="{election_title}"
ADMIN_TOKEN="{admin_token}"
ELECTION_POSITIONS="{positions}"
```

## 📋 Election Positions Configured

{positions_formatted}

## 🗳️ Voter Setup Instructions

### 1. Prepare Voter List
Create a CSV file with columns: `MemberID,FullName,PhoneNumber,VotingToken`

Example:
```csv
MemberID,FullName,PhoneNumber,VotingToken
ORG001,John Doe,+1234567890,12345678
ORG002,Jane Smith,+1234567891,
ORG003,Bob Johnson,+1234567892,87654321
```

### 2. Upload Voters
1. Go to `/admin` on your deployed site
2. Enter admin token: `{admin_token}`
3. Upload your CSV file
4. Generate Voter IDs (system will auto-generate tokens if blank)

### 3. Distribute Credentials
Send each voter their:
- **Voter ID** (e.g., ORG001)
- **8-digit Voting Token** (e.g., 12345678)

## 🎯 System URLs (After Deployment)

- **Home Page**: `https://your-app-url.com/`
- **Voting Page**: `https://your-app-url.com/vote`
- **Admin Panel**: `https://your-app-url.com/admin`
- **Live Dashboard**: `https://your-app-url.com/dashboard`

## Security Features

- Dual Authentication: Voter ID + 8-digit token required
- One-time Use: Each credential set can only vote once
- Anonymous Voting: No linkage between voters and choices
- Real-time Results: Live dashboard updates during election
- Admin Security: Token-based admin access

## 📞 Support

If you need help with deployment or have questions:

1. **Check the logs**: Your deployment platform will show error messages
2. **Verify environment variables**: Make sure all variables are set correctly
3. **Test admin access**: Try logging into `/admin` with your token
4. **Contact support**: Include your deployment URL and error messages

## You're All Set!

Your custom voting system is ready to handle secure, anonymous elections for {org_name}. The system can handle hundreds to thousands of voters with real-time results and complete election transparency.

**Happy Voting!**
"""

    guide_path = os.path.join(output_dir, 'DEPLOYMENT_GUIDE.md')
    with open(guide_path, 'w', encoding='utf-8') as f:
        f.write(guide_content)

    print(f"Created deployment guide: {guide_path}")
    return guide_path

def create_client_package(org_name, election_title, positions, admin_token, output_dir):
    """Create a complete client package with all necessary files"""

    # Create output directory
    os.makedirs(output_dir, exist_ok=True)

    # Create customized files
    env_file = create_env_file(org_name, election_title, positions, admin_token, output_dir)
    guide_file = create_deployment_guide(org_name, election_title, positions, admin_token, output_dir)

    # Copy sample files
    sample_files = [
        'data/sample_voters.csv',
        'README.md'
    ]

    for file_path in sample_files:
        if os.path.exists(file_path):
            dest_path = os.path.join(output_dir, os.path.basename(file_path))
            shutil.copy2(file_path, dest_path)
            print(f"Copied {file_path} to {dest_path}")

    # Create client info summary
    summary = {
        "organization": org_name,
        "election_title": election_title,
        "positions_count": len(positions.split(',')),
        "positions": [pos.strip() for pos in positions.split(',')],
        "admin_token": admin_token,
        "created_files": [
            os.path.basename(env_file),
            os.path.basename(guide_file),
            "sample_voters.csv",
            "README.md"
        ]
    }

    summary_path = os.path.join(output_dir, 'client_summary.json')
    with open(summary_path, 'w') as f:
        json.dump(summary, f, indent=2)

    print(f"Created client summary: {summary_path}")

    return {
        "output_dir": output_dir,
        "files_created": [
            env_file,
            guide_file,
            os.path.join(output_dir, 'sample_voters.csv'),
            os.path.join(output_dir, 'README.md'),
            summary_path
        ],
        "summary": summary
    }

def main():
    parser = argparse.ArgumentParser(description='Create customized voting system deployment for clients')
    parser.add_argument('--org', required=True, help='Organization name')
    parser.add_argument('--election', required=True, help='Election title')
    parser.add_argument('--positions', required=True, help='Comma-separated list of positions')
    parser.add_argument('--admin-token', required=True, help='Admin token for the organization')
    parser.add_argument('--output', default='client_deployment', help='Output directory name')

    args = parser.parse_args()

    print("Universal Voting System - Client Deployment Creator")
    print("=" * 60)
    print(f"Organization: {args.org}")
    print(f"Election: {args.election}")
    print(f"Positions: {args.positions}")
    print(f"Admin Token: {args.admin_token}")
    print(f"Output Directory: {args.output}")
    print("=" * 60)

    result = create_client_package(
        args.org,
        args.election,
        args.positions,
        args.admin_token,
        args.output
    )

    print("\nClient package created successfully!")
    print(f"Output Directory: {result['output_dir']}")
    print("\nFiles Created:")
    for file_path in result['files_created']:
        print(f"  • {os.path.basename(file_path)}")

    print("\nNext Steps:")
    print("  1. Share the deployment package with your client")
    print("  2. Guide them through the DEPLOYMENT_GUIDE.md")
    print("  3. Help them set up their deployment platform")
    print("  4. Assist with voter list preparation and upload")
    print("\nReady for another deployment! Run this script again for the next client.")
if __name__ == '__main__':
    main()